sequenceDiagram
  participant user
  participant TAP/SIA
  participant datalinker
  participant Butler
  participant storage

  user->>+TAP/SIA: Image search
  TAP/SIA->>-user: VOTable w/DataLink URL

  user->>+datalinker: GET DataLink URL
  datalinker->>+Butler: GET signed URL
  Butler<<->>storage: Locate image
  Butler->>-datalinker: Signed 1hr lifetime URL
  datalinker->>-user: DataLink record w/URL

  user->>+storage: GET with signed 1hr lifetime URL
  storage->>-user: Desired image
